In [40]:
'''2). using for loop combination, implement the logic of converting 4x4 matrix to 2x2, by taking 2x2 window size. 
chk the box, the same color is the window and from each window, the maximum value is selected. 
you have to create the logic, where if you feed any 4x4 matrix it should return the 2x2 matrix in this manner.'''



import numpy as np
four=np.array([[10,20,30,0],[8,12,2,0],[34,70,37,4],[112,100,25,12]])
li=[]
li.append(four[0,1])
li.append(four[0,0])
li.append(four[1,0])
li.append(four[1,1])
val=li[0]
for i in li:
    if(i>val):
        val=i 
k=val
li=[]
li.append(four[0,2])
li.append(four[0,3])
li.append(four[1,2])
li.append(four[1,3])
val=li[0]
for i in li:
    if(i>val):
        val=i 
l=val
li=[]
li.append(four[2,0])
li.append(four[2,1])
li.append(four[3,0])
li.append(four[3,1])
val=li[0]
for i in li:
    if(i>val):
        val=i 
m=val
li=[]
li.append(four[2,2])
li.append(four[2,3])
li.append(four[3,2])
li.append(four[3,3])
val=li[0]
for i in li:
    if(i>val):
        val=i 
n=val
two=np.array([[k,l],[m,n]])
print(four,'\n\n\n',two)


[[ 10  20  30   0]
 [  8  12   2   0]
 [ 34  70  37   4]
 [112 100  25  12]] 


 [[ 20  30]
 [112  37]]
